modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/ItsBlackGear/CaveBiomeAPI/issues"

[[mods]]
    modId = "cavebiomeapi"
    version = "1.2.0"
    logoFile = "cavebiomes.png"
    authors = "BlackGear27"
    credits = "BlackGear27, TelepathicGrunt, CorgiTaco"
    displayName = "CaveBiomeAPI"
    description = '''This mod allows developers to add actual underground biomes to give more life to the depths of our beloved worlds!'''

[[dependencies.cavebiomeapi]]
    modId = "forge"
    mandatory = true
    versionRange="[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cavebiomeapi]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "AFTER"
    side = "BOTH"